# Changes here will be overwritten by Copier
_commit: 973c39c
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: jupyter
add_wiki: false
email: dev@1kbgz.com
github: 1kbgz
project_description: Support for notebook templates in jupyter and jupyterlab
project_name: jupyter templates
python_version_primary: '3.11'
team: the jupyter-templates authors
